# .github/workflows/pypi-publish.yml
# SPDX-FileCopyrightText: 2025 David Osipov <personal@david-osipov.vision>
#
# SPDX-License-Identifier: MIT
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows to run this workflow manually from the Actions tab on GitHub UI
  workflow_dispatch:

# Adding explicit permissions following the principle of least privilege
permissions:
  contents: read

jobs:
  verify-tests:
    name: Run tests workflow
    uses: DavidOsipov/gmpy2-stubs/.github/workflows/python-tests.yml@main

  generate-changelog:
    name: Generate Changelog
    needs: [verify-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to update CHANGELOG.md
    steps:
      - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - name: Generate changelog
        uses: rhysd/changelog-from-release/action@52d937b0fb327a34339178db5413662c35213abf
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          pull_request: true

  build-n-publish:
    name: pypi-publish
    needs: [verify-tests, generate-changelog]
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
    - name: Set up Python
      uses: actions/setup-python@fbeb884f69f0ac1c0257302f62aa524c2824b649
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build a binary wheel and a source tarball
      run: |
        hatch build
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@d417ba7e7683fa9104c42abe611c1f2c93c0727d
      with:
        print-hash: true
        verbose: true