# .github/workflows/pypi-publish.yml
# SPDX-FileCopyrightText: 2025 David Osipov <personal@david-osipov.vision>
#
# SPDX-License-Identifier: MIT
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows to run this workflow manually from the Actions tab on GitHub UI
  workflow_dispatch:

# Adding explicit permissions following the principle of least privilege
permissions:
  contents: read

jobs:
  verify-tests:
    name: Run tests workflow
    uses: ./.github/workflows/python-tests.yml

  generate-changelog:
    name: Generate Changelog
    needs: [verify-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to update CHANGELOG.md
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Generate changelog
        uses: rhysd/changelog-from-release/action@589c79eb291056dc380aa43ccfb1f45eebf8c4c3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          pull_request: true

  build-n-publish:
    name: pypi-publish
    needs: [verify-tests, generate-changelog]
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build a binary wheel and a source tarball
      run: |
        hatch build
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@db8f07d3871a0a180efa06b95d467625c19d5d5f
      with:
        print-hash: true
        verbose: true